version: '3'
services:
  python:
    build:
        context: .
        dockerfile: .docker/python/Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    command: python3 main.py
    ports:
      - '8000:8000'
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:14.5-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
